### ISSUE TITLE
部分系统运行直接闪退

### ISSUE THREAD

**Issue by 9uest** [baigae/HeavenlyBypassAV#12]
使用Windows Server 2022 运行直接退出，无法使用，没有任何提示
使用Win10系统 正常

**Comment by baigae** [comment]
师傅说的是免杀马生成器还是免杀马？

**Comment by 9uest** [comment]
免杀马

**Comment by baigae** [comment]
> 免杀马

截图看看？有可能是反沙箱引起的

**Comment by 9uest** [comment]
什么安全软件都没有装，运行后没有什么返回信息，进程大概十几秒后就直接退出了

![Snipaste_2024-11-24_00-08-58](https://github.com/user-attachments/assets/4db37a40-3120-403d-a19a-a355902e26f9)

**Comment by baigae** [comment]
> 息，进程大概十几秒后就直接退出了

你生成免杀马选项是啥？

**Comment by 9uest** [comment]
1.本地分离+2.延时 
经测试，发现在本地和网络分离中，除了 1.判断进程 可以运行外，2.3.4都是无反应

**Comment by baigae** [comment]
> 1.本地分离+2.延时 经测试，发现在本地和网络分离中，除了 1.判断进程 可以运行外，2.3.4都是无反应

反沙箱的原因吧，你这么说
